[package]
name = "oop"
version = "0.1.0"
authors = ["fqliao <fqliao@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "oop"
path = "src/main.rs"

[dependencies]
